# Generated by Django 5.2 on 2025-05-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=15)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("alergias", models.TextField(blank=True)),
                ("antecedentes", models.TextField(blank=True)),
            ],
        ),
    ]
