# Generated by Django 5.2 on 2025-06-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="actividad_fisica",
            field=models.BooleanField(default=False, verbose_name="Actividad física"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="bebe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paciente",
            name="cancer",
            field=models.BooleanField(default=False, verbose_name="Cáncer"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="diabetes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paciente",
            name="distension_despues_comer",
            field=models.BooleanField(
                default=False, verbose_name="Distensión después de comer"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="dolor_estomago",
            field=models.BooleanField(
                default=False, verbose_name="Dolor en la boca del estómago"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="escolaridad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primaria", "Primaria"),
                    ("secundaria", "Secundaria"),
                    ("preparatoria", "Preparatoria"),
                    ("licenciatura", "Licenciatura"),
                    ("especialidad", "Especialidad"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soltero", "Soltero"),
                    ("casado", "Casado"),
                    ("divorciado", "Divorciado"),
                    ("viudo", "Viudo"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="estrenimiento",
            field=models.BooleanField(default=False, verbose_name="Estreñimiento"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="fuma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paciente",
            name="hipertension_arterial",
            field=models.BooleanField(
                default=False, verbose_name="Hipertensión arterial"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="horario_cena",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="horario_comida",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="horario_desayuno",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="medicamentos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="obesidad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paciente",
            name="ocupacion",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paciente",
            name="otra_enfermedad",
            field=models.TextField(blank=True, verbose_name="Otra enfermedad"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="rfc",
            field=models.CharField(blank=True, max_length=13, verbose_name="RFC"),
        ),
    ]
