# Generated by Django 5.2 on 2025-06-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_paciente_actividad_fisica_paciente_bebe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="llave_unica",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
