# Generated by Django 5.2 on 2025-06-22 04:05

from django.db import migrations
import uuid

def generar_uuids_para_existentes(apps, schema_editor):
    Paciente = apps.get_model('pacientes', 'Paciente')
    for paciente in Paciente.objects.filter(llave_unica__isnull=True):
        paciente.llave_unica = uuid.uuid4()
        paciente.save(update_fields=['llave_unica'])


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_paciente_llave_unica"),
    ]

    operations = [
        migrations.RunPython(generar_uuids_para_existentes, reverse_code=migrations.RunPython.noop),]
