# Generated by Django 5.2 on 2025-06-22 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0004_generar_uuids_pacientes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="llave_unica",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Llave Única de Acceso",
            ),
        ),
    ]
