# Generated by Django 5.2 on 2025-05-02 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("peso", models.FloatField(help_text="Peso en kilogramos")),
                ("altura", models.FloatField(help_text="Altura en centímetros")),
                ("imc", models.FloatField(editable=False)),
                ("circunferencia_cintura", models.FloatField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="pacientes.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanNutricional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="consultas.consulta",
                    ),
                ),
            ],
        ),
    ]
