# Generated by Django 5.2 on 2025-06-19 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="circunferencia_cadera",
            field=models.FloatField(blank=True, null=True, verbose_name="Cadera (cm)"),
        ),
        migrations.AddField(
            model_name="consulta",
            name="circunferencia_pecho",
            field=models.FloatField(blank=True, null=True, verbose_name="Pecho (cm)"),
        ),
        migrations.AddField(
            model_name="consulta",
            name="tension_arterial",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="T/A"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="tratamiento",
            field=models.TextField(blank=True, null=True, verbose_name="TX"),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="circunferencia_cintura",
            field=models.FloatField(blank=True, null=True, verbose_name="Cintura (cm)"),
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicamentos",
                    models.TextField(help_text="Lista de medicamentos recetados"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receta",
                        to="consultas.consulta",
                    ),
                ),
            ],
        ),
    ]
