# Generated by Django 5.2 on 2025-07-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0003_remove_plannutricional_contenido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannutricional",
            name="horario_cena",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannutricional",
            name="horario_colacion1",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horario colación 1"
            ),
        ),
        migrations.AddField(
            model_name="plannutricional",
            name="horario_colacion2",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horario colación 2"
            ),
        ),
        migrations.AddField(
            model_name="plannutricional",
            name="horario_comida",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannutricional",
            name="horario_desayuno",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
