# Generated by Django 5.2 on 2025-07-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0004_plannutricional_horario_cena_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannutricional",
            name="contenido_colacion2",
            field=models.TextField(default="", verbose_name="Contenido colación 2"),
        ),
        migrations.AlterField(
            model_name="plannutricional",
            name="contenido_colacion",
            field=models.TextField(default="", verbose_name="Contenido colación 1"),
        ),
    ]
